org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\temp\\jdk17\\jdk-17.0.11+9
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Suppress deprecation warnings
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED

# Enable legacy APIs for kapt compatibility
android.newDsl=false
